apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wqzsd0r73-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wqzsd0r73-go 
  name: wqzsd0r73-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wqzsd0r73-go 
